services:
    _defaults:
        autowire: true
        autoconfigure: true

    NereaEnrique\Search\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
